config/routes.rb
Rails.application.routes.draw do

devise_for :users

  post 'upquantity', to: 'shops#additem'
  post 'downquantity', to: 'shops#removeitem'
  get 'total_price', to: 'shops#total_price'

  resources :shops, only: [:index, :show] do
    member do
      get 'add_to_cart', to: 'orders#add_to_cart'
    end
    member do
      get 'cart'
    end
  end

  resources :orders, only: [:index, :show, :create] do
    resources :order_items, only: [:create, :destroy]
    post 'validate', to: 'orders#validate'
  end
  get '/profile', to: 'orders#index', as: 'profile'

  root to: 'pages#home'

end

app/models/shop.rb
class Shop < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_many :items

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  before_action :store_current_location, :unless => :devise_controller?

  skip_before_action :authenticate_user!, only: [ :index, :show, :cart, :additem, :removeitem, :total_price ]

  def index
    # shop geolocation set-up
    if params[:address].present?
      session[:address] = params[:address]
      @shops = Shop.near(params[:address], 0.5)
    elsif session[:address].present?
      @shops = Shop.near(session[:address], 0.5)
    else
      @shops = Shop.where.not(latitude: nil, longitude: nil)
    end

    @hash = Gmaps4rails.build_markers(@shops) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
      marker.infowindow render_to_string(partial: "/shops/map_box", locals: { shop: shop })
    end

    # setting de params pour récupérer l'adresse à partir de l'autocomplete
    # ajout d'un nouveau marqueur correpondant aux params
    if params[:address].present?
      lat = Geocoder.search(params[:address]).first.geometry['location']['lat']
      lng = Geocoder.search(params[:address]).first.geometry['location']['lng']
      icon = "http://maps.google.com/mapfiles/ms/icons/green.png"

      @hash.push ({lat: lat, lng: lng, picture: {
        url: icon,
        width:  32,
        height: 32
      }})
    end
  end

  def show
    @shop = Shop.find(params[:id])
    reset_cart(params[:id]) unless session[:carts] == nil
    # shop geolocation set-up
    @shop_coordinates = { lat: @shop.latitude, lng: @shop.longitude }

    @hash = Gmaps4rails.build_markers(@shop) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
    end

  end

  def cart
    @shop = Shop.find(params[:id])

    if session[:carts].nil? || session[:carts].empty?
      @item_data = nil
    else
      @item_data = session[:carts][params[:id]].to_a
    end

    @orders = Order.all # TODO : available_orders
  end

  def additem
    session[:carts].first[1][params.first[0]] += 1
    @cart = session[:carts]
    session[:numbcart]['sum'] += 1
    respond_to do |format|
      format.json { render json: session[:carts] }
    end
  end

  def removeitem
    session[:carts].first[1][params.first[0]] -= 1
    @cart = session[:carts]
    session[:numbcart]['sum'] -= 1

    respond_to do |format|
      format.json { render json: session[:carts] }
    end
  end

  def total_price
    sum = 0
    session[:carts].first[1].each { |k,v| sum += Item.find(k.to_i).price * v }
    # total_price = @item_data.map { |x| Item.find(x[0].to_i).price}.inject(:+)

    respond_to do |format|
      format.json { render json: sum }
    end
  end

  private

  def reset_cart(id)
    session[:carts] = {} unless id == session[:carts].keys.first.to_s
    session[:numbcart] = {} unless id == session[:carts].keys.first.to_s#Rom1: remet cette variable de session à zéro si on change de shop
  end

  def shop_params
  params.require(:shop).permit(:name, :address, :latitude, :longitude, :photo)
  end

  def store_current_location
    store_location_for(:user, request.url)
  end
end

app/views/shops/_cart-show-map.html.erb
 <div style='width: 350px;'>
    <div id="map-<%= order.id%>" style='width: 350px; height: 200px;'></div>
</div>

<% content_for(:after_js) do %>
  <script>
    $('#take_away').on('orders-shown', function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({
       internal: {
        id: "map-<%= order.id%>",
        zoom: 1,
        center: ([{ lat: <%= order.user.latitude %>, lng: <%= order.user.longitude %>}]),
        MapOptions: {
        }
      },
      provider: {
      <!-- disable UI content -->
        disableDefaultUI: true,
      <!-- -->
        styles: [{"featureType":"landscape","stylers":[{"saturation":-100},{"lightness":65},{"visibility":"on"}]},{"featureType":"poi","stylers":[{"saturation":-100},{"lightness":51},{"visibility":"simplified"}]},{"featureType":"road.highway","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"road.arterial","stylers":[{"saturation":-100},{"lightness":30},{"visibility":"on"}]},{"featureType":"road.local","stylers":[{"saturation":-100},{"lightness":40},{"visibility":"on"}]},{"featureType":"transit","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"administrative.province","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":-25},{"saturation":-100}]},{"featureType":"water","elementType":"geometry","stylers":[{"hue":"#ffff00"},{"lightness":-25},{"saturation":-97}]}]
        },
      }, function() {
        markers = handler.addMarkers([{ lat: <%= order.user.latitude %>, lng: <%= order.user.longitude %>}]);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 1) {
          handler.getMap().setZoom(16);
       };
    });
  });
  </script>
<% end %>

app/views/shops/_cart_details.html.erb
<div class ='row'>
   <div class="col-sm-12 position_relative_top">
      <div class="col-sm-2 relative_child">
        <i class="fa fa-long-arrow-left" aria-hidden="true"></i><%= link_to ' Back to Coffee shop', shop_path(@shop.id), style:'color:darkgrey' %>
      </div>
        <div class="col-sm-8 text-center">
          <h3 class='menu-subtitle text-center'>1 - Check your order from <%= @shop.name %> </h3>
        </div>
        <div class="col-sm-2 relative_child"></div>
      </div>
    </div>
</div>


<div class ='row text-center'>
  <br>
  <% @total = 0 %>
  <% @item_data.each do |k, v| %>
  <div class='col-sm-3 position_relative'>
    <div class='col-sm-12 position_relative cart_item'>
    <figure class='overlay'>
      <%= cl_image_tag Item.find(k.to_i).photo, width: 256, height: 256, crop: "fill" %>
      <div class='cart_text'>
        <div class="col-sm-5">
          <h4 class='menu-title'><%= Item.find(k.to_i).name %></h4>
        </div>

          <div class='col-sm-2'>
            <h4 class='menu-title' id=<%=k.to_s%>><%=v.to_s%><%= ' x' %></h4>
          </div>
          <div class="col-sm-2">
            <h4 class="menu-title"><%= Item.find(k.to_i).price.round(2).to_s + '€' %></h4>
          </div>

        <div class="col-sm-3">
          <h4 class='menu-title'>
          <i class="fa fa-minus-circle remove_item" id=<%=k.to_s%> aria-hidden="true" style="color:darkgrey"></i>
          <i class="fa fa-plus-circle add_item" id=<%=k.to_s%> aria-hidden="true" style="color:darkgrey"></i>
          </h4>
        </div>
      </div>
      </figure>
    </div>
  </div>

  <% @total += (Item.find(k.to_i).price * v) %>
  <% end %>
</div>

<div class ='row'>
  <br>
    <div class='col-sm-5'></div>
    <div class='col-md-2 text-center menu-subtitle'>
    <div id='total'><%='TOTAL AMOUNT : ' + @total.round(2).to_s + '€' %></div>
    <div class='col-sm-5'></div>
  </div>
</div>

app/views/shops/_cart_pending_orders.html.erb
<br>
<div class='text-center'>
  <h3 class='menu-subtitle'>3 - Take another order in charge for delivery</h3>
</div>

<div>
  <% @total_orders = 0 %>
  <% conteur = 0 %>
  <% @orders.each do |order| %>
    <% break if conteur == 3%>
    <% if order.order_items.first.item.shop_id == @shop.id && order.status == true %>
      <% @total_orders += 1 %>
      <% conteur+=1 %>
      <div class='child col-md-offset-2 col-md-8'>
        <div class='col-md-4'> <!-- bloc Item list -->
          <div>
            <h3>Order n°<%= order.id %></h3>
          </div>
          <div >
            <h4>Items list :</h4>
            <% @total_list = 0 %>
            <% order.order_items.each do |order_item| %>
              <% @total_list += order_item.item.price %>
              <p><%= order_item.item.name + ' - ' + order_item.item.price.to_s + '€' %></p>
            <% end %>
            <h4><%= 'Total : ' + @total_list.to_s + '€' %></h4>
          </div>
        </div>
        <div class='col-md-6'> <!-- bloc Map with direction Render à intégrer / manu -->
          <%= render 'cart-show-map', order: order %>
        </div>
        <div class='col-md-2 text-center'> <!-- select delivery button -->
          <div class='child_order' data-child-id="<%= order.id %>">
            <div class='fa fa-check-circle fa-5x text-center'></div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div>
  <% if @total_orders == 0 %>
    <div class='text-center'>
      <h3 class="module-subtitle">Thanks but no one needs a delivery right now,</h3>
      <h3 class="module-subtitle">you can proceed to your order confirmation below.</h3>
    </div>
  <% end %>
</div>


<!-- @orders.select {|order| condition(order)}.first(3).each do  -->

app/views/shops/_cart_show_empty.html.erb
<div class='container-fluid margin-top-page'>

  <div class='row text-center'>
  <br>
    <%= cl_image_tag 'fallen_coffee_gm6wgy' %>
  </div >

  <div class='row text-center'>
  <br>
    <h3 class="module-subtitle">NICE TRY, BUT YOUR CART IS EMPTY...</h3>
  </div>

  <div class='row text-center'>
    <br>
    <%= link_to 'Back to Coffee shop', shop_path(@shop.id), style:'color:darkgrey' %>
  </div>
</div>

app/views/shops/_delivery_method_choice.html.erb
<div class= 'col-md-6 position_relative' id='take_away' style='background: none'>
    <%= cl_image_tag ("barista_test_cart_zbkngq"), id:'img_take_away' %>
    <span class='delivery_bottom'>TAKE AWAY</span>
</div>

<div class= 'col-md-6 position_relative' id='delivery' style='background: none'>
<%= cl_image_tag ("coffee-delivery4_k3qqyy_m4tqsk"), id:'img_delivery' %>

  <span class='delivery_bottom'>DELIVERY</span>
</div>

app/views/shops/_map_box.html.erb
 <div class="map_box">
    <h4 class="menu-subtitle"><%= shop.name %></h4>
    <p class='menu-detail'><%= shop.address %></p>
    <%= link_to "Details", shop_path(shop), class: "btn btn-custom-1 btn-sm" %>
 </div>

app/views/shops/_shop-show-map.html.erb
<div id="map" style="width: 100%; height: 700px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({
        internal: {
          id: 'map'
        },
        provider: {
          styles: [{"featureType":"landscape","stylers":[{"saturation":-100},{"lightness":65},{"visibility":"on"}]},{"featureType":"poi","stylers":[{"saturation":-100},{"lightness":51},{"visibility":"simplified"}]},{"featureType":"road.highway","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"road.arterial","stylers":[{"saturation":-100},{"lightness":30},{"visibility":"on"}]},{"featureType":"road.local","stylers":[{"saturation":-100},{"lightness":40},{"visibility":"on"}]},{"featureType":"transit","stylers":[{"saturation":-100},{"visibility":"simplified"}]},{"featureType":"administrative.province","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":-25},{"saturation":-100}]},{"featureType":"water","elementType":"geometry","stylers":[{"hue":"#ffff00"},{"lightness":-25},{"saturation":-97}]}]
        }
      }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(16);
        }
      });
    });
  <% end %>
<% end %>

app/views/shops/cart.html.erb
<% if @item_data %>

<%= form_tag orders_path do %>
  <%= hidden_field_tag("order[delivery_type]", "true") %>
  <%= hidden_field_tag("order[child_order_id]", "") %>

  <div class='container-fluid margin-top-page' id='cart_details'>
    <!-- Set the items -->
    <%= render 'cart_details' %>
  </div>

  <div class='container'>
    <br>
    <div class ='row text-center'>
      <h3 class='menu-subtitle'>2 - Select your delivery method</h3>
    </div>


    <div class ='row' id='delivery_method_choice'>
    <!-- Set the delivery method -->
      <%= render 'delivery_method_choice' %>
    </div>


    <div class='row' id='pending_orders' style='display: none'>
      <!-- set the child_order -->
      <%= render 'cart_pending_orders' %>
    </div>

    <div class ='row text-center'>
      <!-- Submit data to create order -->
    <br>
    <br>
      <% session[:carts][params[:id]] %>
      <button class='btn btn-custom-1 btn-lg' type="submit">CONFIRM ORDER(S)</button>

    </div>
    <br>
  </div>
<% end %>

<% content_for :after_js do %>
  <%= javascript_include_tag 'cart.js' %>
<%end%>

<% else %>
    <%= render 'cart_show_empty' %>
<% end %>

app/views/shops/index.html.erb
<div class='container-fluid margin-top-page'>
  <div class='row'>

    <div class="col-sm-6" style="height: 700px;overflow-y:scroll;">
      <% @shops.each do |shop| %>
      <%= link_to shop_path(shop.id, address: @params) do %>
      <div class="col-sm-6">
        <div class="menu-classic text-center">
          <%= cl_image_tag shop.photo, width: 260, height: 170, crop: "fill" %>
          <h4 class='menu-title text-center'><%= shop.name %></h4>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>

    <div class="col-sm-6">
      <div class='map'>
        <div id="map" style="width: 100%; height: 700px;">
        <%= render 'shop-show-map' %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/shops/show.html.erb
<!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "#{@shop.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @shop.description %>
<% content_for :meta_image, cloudinary_url(@shop.photo.path) %>

<div class='container-fluid margin-top-page'>
  <div class='row'>
    <div class="col-sm-12 position_relative_top">
      <div class="col-sm-3 relative_child">
        <i class="fa fa-long-arrow-left" aria-hidden="true"></i><%= link_to ' Back to Coffee Shops', shops_path(address: @params), style:"color:darkgrey" %>
      </div>
      <div class="col-sm-6 text-center">
      <h3 class="menu-subtitle text-center shop"><%= "Coffee's from" + ' ' + @shop.name %></h3>
      </div>
      <div class="col-sm-3 relative_child">
        <div class='pull-right'>
        <a href="#footer_shop"><p class="menu-subtitle text-center shop" style="color:darkgrey"><%= "More info on your Coffee Shop  " %><i class="fa fa-info-circle page-scroll" aria-hidden="true" style="color:darkgrey"></p></i>
        </a>
        </div>
      </div>
    </div>
    <% @shop.items.each do |item| %>
    <div class="col-sm-3">
      <div class="menu">
        <div class="item-description">
          <figure class="overlay">
            <%= cl_image_tag item.photo, width: 256, height: 256, crop: "fill"%>
            <figcaption>
              <div class="caption-inner">
                <div class="overlay-icon">

                  <a href="<%=add_to_cart_shop_path(@shop, item_id: item.id)%>" data-remote="true" class="add-button"></a>
                  <i class="fa fa-plus fa-lg" aria-hidden="true"></i>
                </div>
              </div>
            </figcaption>
          </figure>
        </div>
        <div class="description">
          <div class="col-sm-9">
            <h4 class='menu-title'><%= item.name %></h4>
          </div>
          <div class="col-sm-3 text-center">
            <h4 class='menu-price'><%= item.price.to_s + '€' %></h4>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  </br>
  </br>

  <div class="row footer_shop" id="footer_shop">
    <div class="col-sm-4 footer_shop_padding">
    <h3 class="menu-subtitle"><%= @shop.name %></h3>
    <h4 class='menu-subtitle'><%= @shop.address %></h4>
    <p class='menu-subtitle'><i class="fa fa-phone" aria-hidden="true"></i><%= " " + @shop.phone %></p>
    <p class='menu-detail'><%= @shop.horaries %></p>
    <p class='menu-detail'><%= @shop.description %></p>
    </div>
    <div class="col-sm-8">
      <div id="map" style="width: 100%; height: 300px;">
      <%= render 'shop-show-map' %>
      </div>
    </div>
  </div>

</div>