config/routes.rb
Rails.application.routes.draw do

devise_for :users

  post 'upquantity', to: 'shops#additem'
  post 'downquantity', to: 'shops#removeitem'
  get 'total_price', to: 'shops#total_price'

  resources :shops, only: [:index, :show] do
    member do
      get 'add_to_cart', to: 'orders#add_to_cart'
    end
    member do
      get 'cart'
    end
  end

  resources :orders, only: [:index, :show, :create] do
    resources :order_items, only: [:create, :destroy]
    post 'validate', to: 'orders#validate'
  end
  get '/profile', to: 'orders#index', as: 'profile'

  root to: 'pages#home'

end

app/views/shared/_cart.html.erb
<!-- Cart Icon with basket number of items -->
<% if session[:numbcart].nil? || session[:numbcart].empty?%>
  <div id="icon-basket-status" class="icon-basket icon-navbar"></div>
<% else %>
  <div id="icon-basket-status" class="icon-basket-loaded icon-navbar"></div>
<% end %>

<span id="cart-red-circle" class="cart-items cart-hidden">
  <%= (session[:numbcart].nil? || session[:numbcart].empty?) ? 0 : session[:numbcart]['sum'] %>
</span>
<span id="darkvador" class="visible-message"> Your cart is empty ! </span>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer start -->

  <footer id="footer">

    <div class="row">
      <div class="col-md-12 text-center">
        <ul class="social-links">
          <li><a href="#" class="wow fadeInUp"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#" class="wow fadeInUp" data-wow-delay=".1s"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#" class="wow fadeInUp" data-wow-delay=".2s"><i class="fa fa-google-plus"></i></a></li>
          <li><a href="#" class="wow fadeInUp" data-wow-delay=".3s"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="#" class="wow fadeInUp" data-wow-delay=".4s"><i class="fa fa-pinterest"></i></a></li>
          <li><a href="#" class="wow fadeInUp" data-wow-delay=".5s"><i class="fa fa-envelope"></i></a></li>
        </ul>
      </div>
    </div><!-- .row -->

    <div class="row">
      <div class="col-sm-12">
        <p class="copyright">
          © 2017 <a href="#">Batch-#68 Lille</a> - Full Stack Program.
        </p>
      </div>
    </div><!-- .row -->

  </footer>

  <!-- Footer end -->

app/views/shared/_home_navbar.html.erb
<% current_page?(root_path) ? classe = "navbar navbar-custom navbar-transparent navbar-fixed-top" : classe = "navbar navbar-custom navbar-fixed-top" %>

 <nav class="<%= classe %>" role='navigation'>
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#custom-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%# link_to 'BringMeACoffee', root_path, class: 'navbar-brand' %>
      <%= link_to root_path do %>
        <%= cl_image_tag('logo_bmac_bcjg2r', width: 100, class: "avatar-navbar-margin") %>
      <% end %>
    </div> <!-- end navbar-header -->

    <div class="collapse navbar-collapse" id="custom-collapse">
      <div class="nav navbar-nav navbar-right">

        <ul class="nav navbar-nav navbar-right">

          <!-- Home Menu -->
          <% if current_page?(root_path) %>
            <li class="page-scroll"><a href="#home">Home</a></li>
            <li class="page-scroll"><a href="#services">How it works</a></li>
            <li class="page-scroll"><a href="#gallery">Inspiration</a></li>
          <% end %>

          <!-- Cart Icon -->
          <li class="page-scroll">
            <% (session[:carts].nil? || session[:carts].empty?) ? link = "#" : link = cart_shop_path(session[:carts].keys.first) %>
            <% params[:id].nil? ? datalink = "" : datalink = params[:id] %>
            <%= link_to link, id: "cart-link", 'data-link' => datalink do %>
              <%= render 'shared/cart' %>
            <% end %>
          </li>

          <!-- User Avatar if Signed-in -->
          <li class="page-scroll">
            <% if user_signed_in? %>
              <div class="dropdown">
                <%= link_to '#', class: "dropdown", 'data-toggle' => "dropdown" do %>
                  <% if current_user.photo? %>
                    <%= cl_image_tag current_user.photo, class: "avatar-large avatar-navbar-margin" %>
                  <% else %>
                    <i class="fa fa-user avatar-navbar-margin" aria-hidden="true" style="font-size:30px;color:white;margin-top:11px;margin-left:7px"></i>
                  <% end %>
                <% end %>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Profile', profile_path %></li>
                  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </div>
            <% else %>
            <!-- Login Button if not logged -->
              <%= link_to 'Login', new_user_session_path, class: 'login-btn' %>
            <% end %>
          </li>

        </ul>
      </div>
    </div>

  </div><!-- .container -->

</nav>